---
version: "3.9"
services:
  fullnode:
    container_name: sui
    image: mysten/sui-node:stable
    ports:
    - "9000:9000"
    - "9184:9184"
    expose:
    - "9000"
    - "9184"
    restart: unless-stopped
    volumes:
    - ./fullnode-template.yaml:/sui/fullnode.yaml:ro
    - ./genesis.blob:/sui/genesis.blob:ro
    - suidb:/sui/suidb:rw
    command: ["/usr/local/bin/sui-node", "--config-path", "fullnode.yaml"]
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment:
      WATCHTOWER_NOTIFICATIONS: email
      WATCHTOWER_NOTIFICATION_EMAIL_FROM: notify@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_TO: receiver@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER: smtp.gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT: 587
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER: notify@gmail.com
      WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD: google-application-password
      WATCHTOWER_NOTIFICATION_EMAIL_DELAY: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    command: --debug --cleanup --remove-volumes --interval 60 sui
volumes:
  suidb:
